import type { JournalArticle, Product, Review } from "@/types";

// CSS gradient placeholders — used as visual stand-ins for product images.
// Each product has 4 gradients that layer slight variation / lighting shifts.
const g = (stops: string): string => `linear-gradient(135deg, ${stops})`;
const r = (stops: string): string => `radial-gradient(circle at 30% 30%, ${stops})`;

export const PRODUCTS: Product[] = [
  {
    id: "p01",
    slug: "axis-meridian-low-obsidian",
    name: "Meridian Low · Obsidian",
    brand: "AXIS",
    category: "sneakers",
    subcategory: "low-top",
    price: 245,
    compareAtPrice: 310,
    images: [
      g("#0a0a0a 0%, #2c2c2c 60%, #0a0a0a 100%"),
      r("#2c2c2c 0%, #0a0a0a 60%, #000 100%"),
      g("#1a1a1a 0%, #3a3a3a 50%, #0a0a0a 100%"),
      g("#0a0a0a 0%, #111 70%, #000 100%"),
    ],
    description:
      "The Meridian Low is our flagship silhouette — a hand-finished leather runner built over a cushioned EVA midsole. The Obsidian colourway is fully pigmented, tonally laced, and finished with a matte patina.",
    shortDescription: "Hand-finished leather runner in a full-black pigment.",
    variants: {
      colors: [
        { name: "Obsidian", hex: "#0A0A0A", stock: 18 },
        { name: "Bone", hex: "#F5F2EC", stock: 6 },
        { name: "Volt", hex: "#CCFF00", stock: 3 },
      ],
      sizes: [
        { label: "8", stock: 2 },
        { label: "8.5", stock: 4 },
        { label: "9", stock: 5 },
        { label: "9.5", stock: 0 },
        { label: "10", stock: 6 },
        { label: "10.5", stock: 3 },
        { label: "11", stock: 4 },
        { label: "12", stock: 2 },
      ],
    },
    tags: ["leather", "runner", "unisex", "hand-finished"],
    rating: 4.8,
    reviewCount: 243,
    isBestSeller: true,
    isNew: false,
    isFeatured: true,
    materials:
      "Full-grain Italian leather upper. Recycled EVA midsole. Natural rubber outsole. Cotton canvas lining.",
    careInstructions:
      "Wipe with a damp cloth. Use neutral leather conditioner every 60 days. Air-dry away from direct heat.",
    shippingInfo: "Free carbon-neutral shipping on orders over $75. 30-day returns on unworn pairs.",
    createdAt: "2025-02-14T10:00:00Z",
  },
  {
    id: "p02",
    slug: "axis-meridian-high-bone",
    name: "Meridian High · Bone",
    brand: "AXIS",
    category: "sneakers",
    subcategory: "high-top",
    price: 285,
    images: [
      g("#f5f2ec 0%, #e8e4db 60%, #d6d0c3 100%"),
      r("#ffffff 0%, #f5f2ec 60%, #d6d0c3 100%"),
      g("#e8e4db 0%, #f5f2ec 50%, #d6d0c3 100%"),
      g("#fff 0%, #f5f2ec 70%, #e8e4db 100%"),
    ],
    description:
      "A taller take on our signature runner. The Meridian High sits over the ankle with a padded topline, raw-cut collar and a tonal waxed lace. Bone is our softest off-white, built to age gracefully.",
    shortDescription: "Ankle-height runner in warm off-white leather.",
    variants: {
      colors: [
        { name: "Bone", hex: "#F5F2EC", stock: 10 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 7 },
        { name: "Clay", hex: "#B07A53", stock: 4 },
      ],
      sizes: [
        { label: "7", stock: 1 },
        { label: "8", stock: 3 },
        { label: "9", stock: 4 },
        { label: "10", stock: 2 },
        { label: "11", stock: 3 },
        { label: "12", stock: 1 },
      ],
    },
    tags: ["leather", "high-top", "unisex"],
    rating: 4.7,
    reviewCount: 156,
    isBestSeller: true,
    isNew: true,
    isFeatured: true,
    materials: "Full-grain leather upper. Recycled EVA midsole. Cup-sole natural rubber outsole.",
    careInstructions: "Protect with a neutral leather balm before first wear. Wipe clean. Store with shoe trees.",
    shippingInfo: "Ships within 24 hours from our San Francisco studio.",
    createdAt: "2025-03-20T10:00:00Z",
  },
  {
    id: "p03",
    slug: "axis-aero-trail-volt",
    name: "Aero Trail · Volt",
    brand: "AXIS",
    category: "sneakers",
    subcategory: "trail",
    price: 220,
    images: [
      g("#ccff00 0%, #a8d400 40%, #0a0a0a 100%"),
      r("#dbff2e 0%, #a8d400 60%, #81a100 100%"),
      g("#0a0a0a 0%, #ccff00 100%"),
      g("#a8d400 0%, #ccff00 40%, #0a0a0a 100%"),
    ],
    description:
      "Built for city trails and wet pavement. A sculpted TPU cage holds the foot through uneven terrain; a deep-lug Vibram® outsole keeps you planted. Volt is our signature electric lime.",
    shortDescription: "Technical trail runner with a Vibram® sole.",
    variants: {
      colors: [
        { name: "Volt", hex: "#CCFF00", stock: 12 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 9 },
        { name: "Fog", hex: "#9AA2A2", stock: 5 },
      ],
      sizes: [
        { label: "8", stock: 3 },
        { label: "9", stock: 4 },
        { label: "10", stock: 5 },
        { label: "11", stock: 3 },
        { label: "12", stock: 2 },
      ],
    },
    tags: ["technical", "trail", "waterproof", "vibram"],
    rating: 4.6,
    reviewCount: 98,
    isBestSeller: false,
    isNew: true,
    isFeatured: true,
    materials: "Ripstop nylon upper with TPU overlays. BOA® lacing. Vibram® Megagrip outsole.",
    careInstructions: "Machine-wash cold in a mesh bag. Air-dry. Do not tumble.",
    shippingInfo: "Ships in recyclable packaging. Returns free within 30 days.",
    createdAt: "2025-04-02T10:00:00Z",
  },
  {
    id: "p04",
    slug: "axis-court-classic-ash",
    name: "Court Classic · Ash",
    brand: "AXIS",
    category: "sneakers",
    subcategory: "low-top",
    price: 195,
    images: [
      g("#6b6b66 0%, #a8a296 50%, #6b6b66 100%"),
      r("#a8a296 0%, #6b6b66 60%, #403f3c 100%"),
      g("#54544f 0%, #6b6b66 50%, #a8a296 100%"),
      g("#a8a296 0%, #6b6b66 100%"),
    ],
    description:
      "A tennis-inspired silhouette rebuilt in matte suede. Low-slung, perforated toe box, gum outsole. The Court Classic is our everyday shoe — the one we wear until it falls apart.",
    shortDescription: "Everyday low-top in matte suede.",
    variants: {
      colors: [
        { name: "Ash", hex: "#6B6B66", stock: 14 },
        { name: "Bone", hex: "#F5F2EC", stock: 9 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 11 },
      ],
      sizes: [
        { label: "7", stock: 2 },
        { label: "8", stock: 5 },
        { label: "9", stock: 6 },
        { label: "10", stock: 7 },
        { label: "11", stock: 4 },
        { label: "12", stock: 3 },
      ],
    },
    tags: ["suede", "court", "everyday"],
    rating: 4.5,
    reviewCount: 412,
    isBestSeller: true,
    isNew: false,
    isFeatured: false,
    materials: "Matte suede upper. Gum rubber outsole. Recycled cotton laces.",
    careInstructions: "Brush with a suede brush. Apply suede protector spray once per season.",
    shippingInfo: "Free shipping over $75. 30-day returns.",
    createdAt: "2024-11-15T10:00:00Z",
  },
  {
    id: "p05",
    slug: "axis-monolith-boot-obsidian",
    name: "Monolith Boot · Obsidian",
    brand: "AXIS",
    category: "sneakers",
    subcategory: "boot",
    price: 395,
    images: [
      g("#0a0a0a 0%, #1a1a1a 40%, #2c2c2c 100%"),
      r("#2c2c2c 0%, #0a0a0a 50%, #000 100%"),
      g("#1a1a1a 0%, #0a0a0a 70%, #000 100%"),
      g("#111 0%, #1a1a1a 40%, #0a0a0a 100%"),
    ],
    description:
      "An architectural boot on a lug sole. Oiled full-grain leather darkens with wear; the speed-lacing system cinches around a padded collar.",
    shortDescription: "Oiled-leather lug boot for urban wear.",
    variants: {
      colors: [
        { name: "Obsidian", hex: "#0A0A0A", stock: 7 },
        { name: "Clay", hex: "#B07A53", stock: 5 },
      ],
      sizes: [
        { label: "8", stock: 1 },
        { label: "9", stock: 2 },
        { label: "10", stock: 3 },
        { label: "11", stock: 1 },
        { label: "12", stock: 0 },
      ],
    },
    tags: ["leather", "boot", "vibram", "winter"],
    rating: 4.9,
    reviewCount: 64,
    isBestSeller: false,
    isNew: true,
    isFeatured: true,
    materials: "Oiled full-grain leather. Goodyear-welt construction. Vibram® lug outsole.",
    careInstructions: "Condition monthly with saddle oil. Store with cedar shoe trees.",
    shippingInfo: "Ships in a reinforced kraft box. Free returns within 30 days.",
    createdAt: "2025-01-05T10:00:00Z",
  },
  {
    id: "p06",
    slug: "axis-shell-jacket-obsidian",
    name: "Technical Shell Jacket",
    brand: "AXIS",
    category: "apparel",
    subcategory: "outerwear",
    price: 425,
    compareAtPrice: 520,
    images: [
      g("#0a0a0a 0%, #2c2c2c 50%, #0a0a0a 100%"),
      r("#333 0%, #0a0a0a 60%, #000 100%"),
      g("#0a0a0a 0%, #1a1a1a 70%, #000 100%"),
      g("#1a1a1a 0%, #0a0a0a 100%"),
    ],
    description:
      "A 3-layer waterproof shell with taped seams, YKK® AquaGuard zippers and a helmet-compatible hood. Cut oversized to layer over a mid-weight knit.",
    shortDescription: "Waterproof 3-layer shell with taped seams.",
    variants: {
      colors: [
        { name: "Obsidian", hex: "#0A0A0A", stock: 12 },
        { name: "Forest", hex: "#2F4A3A", stock: 8 },
        { name: "Bone", hex: "#F5F2EC", stock: 5 },
      ],
      sizes: [
        { label: "XS", stock: 2 },
        { label: "S", stock: 4 },
        { label: "M", stock: 6 },
        { label: "L", stock: 5 },
        { label: "XL", stock: 3 },
        { label: "XXL", stock: 1 },
      ],
    },
    tags: ["waterproof", "shell", "technical"],
    rating: 4.8,
    reviewCount: 132,
    isBestSeller: true,
    isNew: false,
    isFeatured: true,
    materials: "3-layer bluesign® recycled nylon face. DWR finish. YKK® AquaGuard zippers.",
    careInstructions: "Machine-wash cold with technical wash. Tumble low to reactivate DWR.",
    shippingInfo: "Free shipping over $75.",
    createdAt: "2025-02-02T10:00:00Z",
  },
  {
    id: "p07",
    slug: "axis-heavyweight-hoodie-bone",
    name: "Heavyweight Hoodie · Bone",
    brand: "AXIS",
    category: "apparel",
    subcategory: "knits",
    price: 165,
    images: [
      g("#f5f2ec 0%, #e8e4db 60%, #d6d0c3 100%"),
      r("#fff 0%, #f5f2ec 60%, #d6d0c3 100%"),
      g("#f5f2ec 0%, #fff 70%, #e8e4db 100%"),
      g("#e8e4db 0%, #f5f2ec 100%"),
    ],
    description:
      "A proper hoodie — 520 gsm loopback cotton, dropped shoulder, raw-hem cuffs, metal tipped drawcords. Washed for a broken-in feel from day one.",
    shortDescription: "520 gsm loopback cotton hoodie.",
    variants: {
      colors: [
        { name: "Bone", hex: "#F5F2EC", stock: 20 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 18 },
        { name: "Ash", hex: "#6B6B66", stock: 11 },
      ],
      sizes: [
        { label: "XS", stock: 4 },
        { label: "S", stock: 6 },
        { label: "M", stock: 8 },
        { label: "L", stock: 7 },
        { label: "XL", stock: 5 },
        { label: "XXL", stock: 2 },
      ],
    },
    tags: ["cotton", "hoodie", "heavyweight"],
    rating: 4.9,
    reviewCount: 305,
    isBestSeller: true,
    isNew: false,
    isFeatured: true,
    materials: "100% organic loopback cotton, 520 gsm. Metal-tipped drawcords. Twill-taped shoulders.",
    careInstructions: "Wash cold inside out. Tumble low.",
    shippingInfo: "Free shipping over $75.",
    createdAt: "2024-09-12T10:00:00Z",
  },
  {
    id: "p08",
    slug: "axis-merino-crew-forest",
    name: "Merino Crew · Forest",
    brand: "AXIS",
    category: "apparel",
    subcategory: "knits",
    price: 210,
    images: [
      g("#2f4a3a 0%, #1e3528 60%, #2f4a3a 100%"),
      r("#3a5a47 0%, #2f4a3a 60%, #142218 100%"),
      g("#1e3528 0%, #2f4a3a 50%, #3a5a47 100%"),
      g("#2f4a3a 0%, #1e3528 100%"),
    ],
    description:
      "A fine-gauge merino crew in 100% extra-fine wool. Warm, breathable, wrinkle-free. Travels well and wears like a second skin.",
    shortDescription: "Extra-fine merino wool crewneck.",
    variants: {
      colors: [
        { name: "Forest", hex: "#2F4A3A", stock: 9 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 12 },
        { name: "Bone", hex: "#F5F2EC", stock: 8 },
      ],
      sizes: [
        { label: "S", stock: 3 },
        { label: "M", stock: 5 },
        { label: "L", stock: 4 },
        { label: "XL", stock: 2 },
      ],
    },
    tags: ["merino", "wool", "knit"],
    rating: 4.7,
    reviewCount: 88,
    isBestSeller: false,
    isNew: true,
    isFeatured: false,
    materials: "100% extra-fine Italian merino wool, 17.5 micron.",
    careInstructions: "Hand-wash cold with wool detergent. Lay flat to dry.",
    shippingInfo: "Ships in recyclable wool-friendly packaging.",
    createdAt: "2025-03-11T10:00:00Z",
  },
  {
    id: "p09",
    slug: "axis-utility-trouser-ash",
    name: "Utility Trouser · Ash",
    brand: "AXIS",
    category: "apparel",
    subcategory: "pants",
    price: 195,
    images: [
      g("#6b6b66 0%, #54544f 50%, #403f3c 100%"),
      r("#a8a296 0%, #6b6b66 60%, #403f3c 100%"),
      g("#54544f 0%, #6b6b66 100%"),
      g("#6b6b66 0%, #a8a296 100%"),
    ],
    description:
      "A modern utility trouser cut from Japanese ripstop. Articulated knees, seven pockets, tonal stitching and a concealed drawcord waist.",
    shortDescription: "Ripstop utility trouser with seven pockets.",
    variants: {
      colors: [
        { name: "Ash", hex: "#6B6B66", stock: 10 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 13 },
      ],
      sizes: [
        { label: "S", stock: 4 },
        { label: "M", stock: 5 },
        { label: "L", stock: 4 },
        { label: "XL", stock: 2 },
      ],
    },
    tags: ["ripstop", "utility", "japanese"],
    rating: 4.6,
    reviewCount: 71,
    isBestSeller: false,
    isNew: false,
    isFeatured: false,
    materials: "100% Japanese cotton ripstop, 220 gsm. YKK® hardware.",
    careInstructions: "Machine-wash cold. Hang-dry.",
    shippingInfo: "Free shipping over $75.",
    createdAt: "2024-12-18T10:00:00Z",
  },
  {
    id: "p10",
    slug: "axis-wide-leg-denim-indigo",
    name: "Wide-Leg Denim · Indigo",
    brand: "AXIS",
    category: "apparel",
    subcategory: "pants",
    price: 220,
    images: [
      g("#1a2a44 0%, #253a5c 50%, #0f1828 100%"),
      r("#2a4069 0%, #1a2a44 60%, #0f1828 100%"),
      g("#253a5c 0%, #1a2a44 100%"),
      g("#1a2a44 0%, #253a5c 100%"),
    ],
    description:
      "Rigid 14 oz selvedge denim, woven in Okayama. Cut wide from the hip through a straight leg. Finishes with age.",
    shortDescription: "14 oz Japanese selvedge denim, wide leg.",
    variants: {
      colors: [{ name: "Indigo", hex: "#1a2a44", stock: 11 }],
      sizes: [
        { label: "S", stock: 3 },
        { label: "M", stock: 4 },
        { label: "L", stock: 3 },
        { label: "XL", stock: 1 },
      ],
    },
    tags: ["denim", "selvedge", "japanese"],
    rating: 4.8,
    reviewCount: 57,
    isBestSeller: false,
    isNew: true,
    isFeatured: true,
    materials: "14 oz Kaihara selvedge denim. Copper rivets.",
    careInstructions: "Wash sparingly, inside-out, cold. Hang-dry.",
    shippingInfo: "Ships in recycled kraft.",
    createdAt: "2025-04-10T10:00:00Z",
  },
  {
    id: "p11",
    slug: "axis-graphic-tee-obsidian",
    name: "Mark Graphic Tee",
    brand: "AXIS",
    category: "apparel",
    subcategory: "tees",
    price: 65,
    images: [
      g("#0a0a0a 0%, #1a1a1a 50%, #0a0a0a 100%"),
      r("#2c2c2c 0%, #0a0a0a 60%, #000 100%"),
      g("#1a1a1a 0%, #0a0a0a 100%"),
      g("#0a0a0a 0%, #111 100%"),
    ],
    description:
      "A heavyweight 250 gsm tee in a relaxed box fit. Screen-printed with our studio mark on the chest and a tonal axis logo at the back hem.",
    shortDescription: "250 gsm boxy tee with studio graphic.",
    variants: {
      colors: [
        { name: "Obsidian", hex: "#0A0A0A", stock: 25 },
        { name: "Bone", hex: "#F5F2EC", stock: 22 },
        { name: "Volt", hex: "#CCFF00", stock: 8 },
      ],
      sizes: [
        { label: "XS", stock: 6 },
        { label: "S", stock: 9 },
        { label: "M", stock: 12 },
        { label: "L", stock: 10 },
        { label: "XL", stock: 6 },
      ],
    },
    tags: ["tee", "graphic", "heavyweight"],
    rating: 4.7,
    reviewCount: 520,
    isBestSeller: true,
    isNew: false,
    isFeatured: false,
    materials: "100% combed cotton, 250 gsm. Water-based inks.",
    careInstructions: "Wash inside out, cold. Do not iron print.",
    shippingInfo: "Ships within 24 hours.",
    createdAt: "2024-08-05T10:00:00Z",
  },
  {
    id: "p12",
    slug: "axis-field-cap-obsidian",
    name: "Field Cap · Obsidian",
    brand: "AXIS",
    category: "accessories",
    subcategory: "caps",
    price: 55,
    images: [
      g("#0a0a0a 0%, #2c2c2c 60%, #0a0a0a 100%"),
      r("#1a1a1a 0%, #0a0a0a 60%, #000 100%"),
      g("#2c2c2c 0%, #0a0a0a 100%"),
      g("#0a0a0a 0%, #1a1a1a 100%"),
    ],
    description:
      "A low-profile 5-panel cap in waxed cotton. Curved brim, brass snap-back, embroidered axis mark at the back panel.",
    shortDescription: "Waxed-cotton 5-panel cap.",
    variants: {
      colors: [
        { name: "Obsidian", hex: "#0A0A0A", stock: 30 },
        { name: "Bone", hex: "#F5F2EC", stock: 18 },
        { name: "Forest", hex: "#2F4A3A", stock: 12 },
      ],
      sizes: [{ label: "One size", stock: 60 }],
    },
    tags: ["cap", "waxed", "accessories"],
    rating: 4.5,
    reviewCount: 189,
    isBestSeller: true,
    isNew: false,
    isFeatured: false,
    materials: "Waxed cotton canvas. Brass hardware.",
    careInstructions: "Spot-clean only. Re-wax with neutral fabric wax annually.",
    shippingInfo: "Ships in a kraft mailer.",
    createdAt: "2024-10-22T10:00:00Z",
  },
  {
    id: "p13",
    slug: "axis-carryall-tote-bone",
    name: "Carryall Tote · Bone",
    brand: "AXIS",
    category: "accessories",
    subcategory: "bags",
    price: 145,
    images: [
      g("#f5f2ec 0%, #e8e4db 50%, #d6d0c3 100%"),
      r("#fff 0%, #f5f2ec 60%, #d6d0c3 100%"),
      g("#e8e4db 0%, #f5f2ec 100%"),
      g("#f5f2ec 0%, #fff 100%"),
    ],
    description:
      "A structured tote in 18 oz waxed canvas with vegetable-tanned leather handles. Internal sleeve for a 16\" laptop. Big enough for a week's groceries or a long weekend.",
    shortDescription: "18 oz waxed canvas tote with leather handles.",
    variants: {
      colors: [
        { name: "Bone", hex: "#F5F2EC", stock: 9 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 11 },
      ],
      sizes: [{ label: "One size", stock: 20 }],
    },
    tags: ["bag", "tote", "waxed"],
    rating: 4.8,
    reviewCount: 112,
    isBestSeller: false,
    isNew: true,
    isFeatured: true,
    materials: "18 oz waxed cotton canvas. Vegetable-tanned leather handles. YKK® zip.",
    careInstructions: "Spot-clean with a damp cloth.",
    shippingInfo: "Free shipping.",
    createdAt: "2025-03-29T10:00:00Z",
  },
  {
    id: "p14",
    slug: "axis-leather-card-holder-obsidian",
    name: "Card Holder · Obsidian",
    brand: "AXIS",
    category: "accessories",
    subcategory: "wallets",
    price: 85,
    images: [
      g("#0a0a0a 0%, #1a1a1a 60%, #0a0a0a 100%"),
      r("#2c2c2c 0%, #0a0a0a 60%, #000 100%"),
      g("#1a1a1a 0%, #0a0a0a 100%"),
      g("#0a0a0a 0%, #111 100%"),
    ],
    description:
      "A minimalist card holder in Italian vegetable-tanned leather. Three pockets, one full-width slip. Develops a rich patina with daily use.",
    shortDescription: "Vegetable-tanned leather card holder.",
    variants: {
      colors: [
        { name: "Obsidian", hex: "#0A0A0A", stock: 22 },
        { name: "Clay", hex: "#B07A53", stock: 14 },
      ],
      sizes: [{ label: "One size", stock: 36 }],
    },
    tags: ["wallet", "leather", "edc"],
    rating: 4.9,
    reviewCount: 267,
    isBestSeller: true,
    isNew: false,
    isFeatured: false,
    materials: "Vegetable-tanned Italian leather. Waxed linen thread.",
    careInstructions: "Condition once a year with neutral leather balm.",
    shippingInfo: "Ships in a cotton pouch.",
    createdAt: "2024-07-01T10:00:00Z",
  },
  {
    id: "p15",
    slug: "axis-optical-frames-fog",
    name: "Optical Frames · Fog",
    brand: "AXIS",
    category: "accessories",
    subcategory: "eyewear",
    price: 235,
    images: [
      g("#9aa2a2 0%, #6b6b66 50%, #403f3c 100%"),
      r("#c0c6c6 0%, #9aa2a2 60%, #54544f 100%"),
      g("#9aa2a2 0%, #6b6b66 100%"),
      g("#6b6b66 0%, #9aa2a2 100%"),
    ],
    description:
      "Bio-acetate optical frames with hand-polished edges and custom barrel hinges. Supplied with prescription-ready demo lenses.",
    shortDescription: "Bio-acetate frames, hand-polished.",
    variants: {
      colors: [
        { name: "Fog", hex: "#9AA2A2", stock: 6 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 8 },
      ],
      sizes: [{ label: "One size", stock: 14 }],
    },
    tags: ["eyewear", "frames", "bio-acetate"],
    rating: 4.6,
    reviewCount: 42,
    isBestSeller: false,
    isNew: true,
    isFeatured: true,
    materials: "Italian bio-acetate. Custom stainless barrel hinges.",
    careInstructions: "Clean with microfibre. Avoid paper towels.",
    shippingInfo: "Ships in a hard case with pouch.",
    createdAt: "2025-04-18T10:00:00Z",
  },
  {
    id: "p16",
    slug: "axis-crew-socks-3pack",
    name: "Crew Socks · 3-pack",
    brand: "AXIS",
    category: "accessories",
    subcategory: "socks",
    price: 38,
    images: [
      g("#f5f2ec 0%, #0a0a0a 50%, #6b6b66 100%"),
      r("#e8e4db 0%, #0a0a0a 60%, #6b6b66 100%"),
      g("#0a0a0a 0%, #f5f2ec 100%"),
      g("#6b6b66 0%, #f5f2ec 100%"),
    ],
    description:
      "Three pairs of combed-cotton crew socks in a tonal set: obsidian, bone and ash. Flat-toe seam. Reinforced heel.",
    shortDescription: "3-pack of combed-cotton crew socks.",
    variants: {
      colors: [{ name: "Tonal", hex: "#6B6B66", stock: 45 }],
      sizes: [
        { label: "S", stock: 15 },
        { label: "M", stock: 20 },
        { label: "L", stock: 10 },
      ],
    },
    tags: ["socks", "cotton", "pack"],
    rating: 4.7,
    reviewCount: 356,
    isBestSeller: true,
    isNew: false,
    isFeatured: false,
    materials: "80% combed cotton, 18% polyamide, 2% elastane.",
    careInstructions: "Machine-wash cold.",
    shippingInfo: "Ships in recyclable mailer.",
    createdAt: "2024-05-10T10:00:00Z",
  },
  {
    id: "p17",
    slug: "axis-commuter-scarf-bone",
    name: "Commuter Scarf · Bone",
    brand: "AXIS",
    category: "accessories",
    subcategory: "scarves",
    price: 115,
    images: [
      g("#f5f2ec 0%, #d6d0c3 60%, #a8a296 100%"),
      r("#fff 0%, #f5f2ec 60%, #d6d0c3 100%"),
      g("#d6d0c3 0%, #f5f2ec 100%"),
      g("#e8e4db 0%, #f5f2ec 100%"),
    ],
    description:
      "A long, soft scarf woven in 100% lambswool. Matte-fringed ends. The kind of scarf you forget on a chair and regret for years.",
    shortDescription: "Lambswool scarf with matte-fringed ends.",
    variants: {
      colors: [
        { name: "Bone", hex: "#F5F2EC", stock: 12 },
        { name: "Forest", hex: "#2F4A3A", stock: 7 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 9 },
      ],
      sizes: [{ label: "One size", stock: 28 }],
    },
    tags: ["scarf", "wool", "lambswool"],
    rating: 4.8,
    reviewCount: 76,
    isBestSeller: false,
    isNew: true,
    isFeatured: true,
    materials: "100% lambswool, woven in Scotland.",
    careInstructions: "Dry-clean only.",
    shippingInfo: "Ships in recycled tissue wrap.",
    createdAt: "2025-03-02T10:00:00Z",
  },
  {
    id: "p18",
    slug: "axis-training-short-volt",
    name: "Training Short · Volt",
    brand: "AXIS",
    category: "apparel",
    subcategory: "shorts",
    price: 85,
    images: [
      g("#ccff00 0%, #a8d400 50%, #81a100 100%"),
      r("#dbff2e 0%, #ccff00 60%, #81a100 100%"),
      g("#a8d400 0%, #ccff00 100%"),
      g("#ccff00 0%, #5f7600 100%"),
    ],
    description:
      "A 5-inch training short in four-way-stretch nylon. Built-in liner, zipped rear pocket, reflective axis mark.",
    shortDescription: "Four-way-stretch training short.",
    variants: {
      colors: [
        { name: "Volt", hex: "#CCFF00", stock: 14 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 16 },
      ],
      sizes: [
        { label: "S", stock: 5 },
        { label: "M", stock: 7 },
        { label: "L", stock: 6 },
        { label: "XL", stock: 3 },
      ],
    },
    tags: ["training", "performance", "shorts"],
    rating: 4.4,
    reviewCount: 91,
    isBestSeller: false,
    isNew: true,
    isFeatured: false,
    materials: "88% recycled nylon, 12% elastane.",
    careInstructions: "Machine-wash cold. Do not tumble.",
    shippingInfo: "Free shipping over $75.",
    createdAt: "2025-04-05T10:00:00Z",
  },
  {
    id: "p19",
    slug: "axis-overshirt-clay",
    name: "Overshirt · Clay",
    brand: "AXIS",
    category: "apparel",
    subcategory: "outerwear",
    price: 240,
    compareAtPrice: 295,
    images: [
      g("#b07a53 0%, #8f5d3a 50%, #6b4225 100%"),
      r("#c89875 0%, #b07a53 60%, #6b4225 100%"),
      g("#8f5d3a 0%, #b07a53 100%"),
      g("#b07a53 0%, #c89875 100%"),
    ],
    description:
      "A boxy overshirt cut from 12 oz Japanese herringbone. Twin chest pockets, horn buttons, French seams throughout.",
    shortDescription: "12 oz herringbone overshirt with horn buttons.",
    variants: {
      colors: [
        { name: "Clay", hex: "#B07A53", stock: 8 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 10 },
      ],
      sizes: [
        { label: "S", stock: 3 },
        { label: "M", stock: 4 },
        { label: "L", stock: 3 },
        { label: "XL", stock: 1 },
      ],
    },
    tags: ["overshirt", "herringbone", "japanese"],
    rating: 4.7,
    reviewCount: 54,
    isBestSeller: false,
    isNew: true,
    isFeatured: true,
    materials: "100% Japanese cotton herringbone, 12 oz. Horn buttons.",
    careInstructions: "Machine-wash cold. Hang-dry.",
    shippingInfo: "Free shipping over $75.",
    createdAt: "2025-03-25T10:00:00Z",
  },
  {
    id: "p20",
    slug: "axis-archive-runner-ember",
    name: "Archive Runner · Ember",
    brand: "AXIS",
    category: "archive",
    subcategory: "runner",
    price: 285,
    compareAtPrice: 355,
    images: [
      g("#e11d2e 0%, #b91c1c 50%, #7f1d1d 100%"),
      r("#ef4444 0%, #e11d2e 60%, #7f1d1d 100%"),
      g("#b91c1c 0%, #e11d2e 100%"),
      g("#e11d2e 0%, #ef4444 100%"),
    ],
    description:
      "From the archive — our first runner in the Ember colourway, reissued one final time. Only 200 pairs produced worldwide.",
    shortDescription: "Limited reissue · 200 pairs worldwide.",
    variants: {
      colors: [{ name: "Ember", hex: "#E11D2E", stock: 4 }],
      sizes: [
        { label: "9", stock: 1 },
        { label: "10", stock: 2 },
        { label: "11", stock: 1 },
      ],
    },
    tags: ["archive", "limited", "runner"],
    rating: 5.0,
    reviewCount: 18,
    isBestSeller: false,
    isNew: true,
    isFeatured: true,
    materials: "Leather upper. Recycled EVA midsole. Natural rubber outsole.",
    careInstructions: "Wipe clean. Condition every 60 days.",
    shippingInfo: "Ships in numbered archive box.",
    createdAt: "2025-04-20T10:00:00Z",
  },
  {
    id: "p21",
    slug: "axis-work-cap-volt",
    name: "Work Cap · Volt",
    brand: "AXIS",
    category: "accessories",
    subcategory: "caps",
    price: 45,
    images: [
      g("#ccff00 0%, #a8d400 50%, #0a0a0a 100%"),
      r("#dbff2e 0%, #ccff00 60%, #81a100 100%"),
      g("#a8d400 0%, #ccff00 100%"),
      g("#ccff00 0%, #0a0a0a 100%"),
    ],
    description:
      "An unstructured work cap in heavyweight cotton twill. Self-fabric strap, antiqued brass slide.",
    shortDescription: "Unstructured cotton-twill work cap.",
    variants: {
      colors: [
        { name: "Volt", hex: "#CCFF00", stock: 20 },
        { name: "Obsidian", hex: "#0A0A0A", stock: 26 },
      ],
      sizes: [{ label: "One size", stock: 46 }],
    },
    tags: ["cap", "cotton", "workwear"],
    rating: 4.5,
    reviewCount: 122,
    isBestSeller: false,
    isNew: false,
    isFeatured: false,
    materials: "Heavyweight cotton twill. Antiqued brass hardware.",
    careInstructions: "Spot-clean.",
    shippingInfo: "Ships in kraft mailer.",
    createdAt: "2024-09-25T10:00:00Z",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getFeaturedProducts(limit: number = 4): Product[] {
  return PRODUCTS.filter((p) => p.isFeatured).slice(0, limit);
}

export function getBestSellers(limit: number = 8): Product[] {
  return PRODUCTS.filter((p) => p.isBestSeller).slice(0, limit);
}

export function getNewArrivals(limit: number = 6): Product[] {
  return PRODUCTS.filter((p) => p.isNew).slice(0, limit);
}

export function getRelatedProducts(product: Product, limit: number = 4): Product[] {
  return PRODUCTS.filter((p) => p.id !== product.id && p.category === product.category).slice(0, limit);
}

export const REVIEWS: Review[] = [
  {
    id: "r1",
    productId: "p01",
    author: "Sofia M.",
    rating: 5,
    title: "The shoe I reach for every day",
    body: "The leather broke in perfectly within a week. The fit runs true to size and the cushioning is quietly excellent. I stopped buying sneakers after this one.",
    createdAt: "2025-03-12T10:00:00Z",
    verified: true,
  },
  {
    id: "r2",
    productId: "p01",
    author: "Marco L.",
    rating: 5,
    title: "Built like furniture",
    body: "These feel structural. Heavy in hand, light on foot. Received endless compliments in the first week.",
    createdAt: "2025-02-28T10:00:00Z",
    verified: true,
  },
  {
    id: "r3",
    productId: "p01",
    author: "Devon R.",
    rating: 4,
    title: "Great — sized up half",
    body: "Runs a touch narrow. Going half up was the right call. Otherwise faultless.",
    createdAt: "2025-02-20T10:00:00Z",
    verified: true,
  },
  {
    id: "r4",
    productId: "p02",
    author: "Amira K.",
    rating: 5,
    title: "The bone ages beautifully",
    body: "Wore them through rain on day three and they got better. The color is complex — somewhere between cream and sand.",
    createdAt: "2025-04-01T10:00:00Z",
    verified: true,
  },
  {
    id: "r5",
    productId: "p07",
    author: "Jonas T.",
    rating: 5,
    title: "The last hoodie you'll buy",
    body: "520 gsm hits different. It has weight. The cut is relaxed without being sloppy. Goes with literally everything.",
    createdAt: "2025-01-18T10:00:00Z",
    verified: true,
  },
  {
    id: "r6",
    productId: "p06",
    author: "Lena O.",
    rating: 5,
    title: "Actually waterproof",
    body: "Tested in a genuine Pacific Northwest downpour. Stayed completely dry. The cut is oversized which I like for layering.",
    createdAt: "2025-03-05T10:00:00Z",
    verified: true,
  },
  {
    id: "r7",
    productId: "p03",
    author: "Ravi B.",
    rating: 4,
    title: "Grippy in the wet",
    body: "The Vibram outsole is legitimate. Took them through wet pavement, packed dirt and gravel. Color is louder in person.",
    createdAt: "2025-04-12T10:00:00Z",
    verified: true,
  },
  {
    id: "r8",
    productId: "p14",
    author: "Helene P.",
    rating: 5,
    title: "Slim, durable, beautiful patina",
    body: "Six months in and the leather is starting to show a real patina. Fits 4 cards + folded bills without bulk.",
    createdAt: "2024-10-22T10:00:00Z",
    verified: true,
  },
];

export function getReviewsForProduct(productId: string): Review[] {
  return REVIEWS.filter((r) => r.productId === productId);
}

export const JOURNAL_ARTICLES: JournalArticle[] = [
  {
    slug: "field-notes-issue-07",
    title: "Field Notes, Issue 07 — The Architecture of a Sneaker",
    excerpt:
      "We spent a week at our leather atelier in Montebelluna watching a Meridian Low become itself. Here are the notes.",
    author: "Studio AXIS",
    date: "2025-04-18T10:00:00Z",
    readMinutes: 7,
    category: "Studio",
    cover: g("#0a0a0a 0%, #2c2c2c 50%, #0a0a0a 100%"),
    content: [
      "There is a room in Montebelluna where the air smells permanently of leather and beeswax. The light is low, the machines are old, and the ceiling is too high for the building. This is where the Meridian is cut, sewn and finished.",
      "A sneaker is not a sculptural object in the way a chair is. It has to move. A shoe is a shape that survives being folded in half, twisted, stepped on, soaked, dried and stepped on again. Every stitch is a compromise between softness and structure.",
      "We start with the lasts. Then the panels. Then the lining. The upper is closed before the sole is even considered. A good sole bonds the shoe to gravity. A great sole does it invisibly.",
      "The Meridian has seven panels. It used to have nine. Every year we try to remove one more — but the last two remain, because structure without continuity looks like a kit.",
    ],
  },
  {
    slug: "why-we-made-the-volt",
    title: "Why We Made the Volt Colourway",
    excerpt:
      "A single colour, loud enough to carry a season. A short essay on restraint, and when to abandon it.",
    author: "Milo Reyes, Design",
    date: "2025-03-28T10:00:00Z",
    readMinutes: 4,
    category: "Design",
    cover: g("#ccff00 0%, #a8d400 60%, #0a0a0a 100%"),
    content: [
      "We wear black. We wear bone. We wear ash. And then once a season we abandon all of that and release something electric.",
      "The Volt colourway began as an accident — a rejected Pantone swatch taped to the wall for six months. It stayed on the wall because no one could stop looking at it.",
      "Loud colour is a design tool. Used correctly it defines the rest of the palette. Everything else becomes the quiet room around it.",
    ],
  },
  {
    slug: "how-to-care-for-leather",
    title: "How to Care for Leather, Properly",
    excerpt:
      "Leather outlives us. Here is how to help it age well.",
    author: "Studio AXIS",
    date: "2025-02-14T10:00:00Z",
    readMinutes: 5,
    category: "Care",
    cover: g("#b07a53 0%, #6b4225 50%, #b07a53 100%"),
    content: [
      "Leather is skin. It needs to be wiped, conditioned and rested. That's most of the story.",
      "Condition every 60 days with a neutral leather balm. Not polish. Polish fills the grain; balm feeds it.",
      "Store with cedar shoe trees. Alternate pairs. Never dry near a radiator.",
    ],
  },
];

export function getArticleBySlug(slug: string): JournalArticle | undefined {
  return JOURNAL_ARTICLES.find((a) => a.slug === slug);
}
